<?php
// Text
$_['text_language']             = 'Language';
$_['home_advertise_article']    = 'WholesaleBox covered in Economic times <a href="http://articles.economictimes.indiatimes.com/2015-12-10/news/68930627_1_customer-loyalty-small-traders-smes" target="_blank" class="fancybox fancybox.iframe"> - Click Here</a> to read full article. 3000+ shops buy hassle free from WholesaleBox';
$_['dealoftheday_link']         = 'index.php?route=product/category/dealOfTheDay';


$_['text_tabs_bottom_1'] = 'We bring you the best prices, as we operate at very low margins, if you compare us with a normal Wholesaler nearby you. Buying from us, you can save 25%-35% of the procurement cost on every order. We have more than %s+ designs on our website for retailers with convenience of e-commerce like COD, Home Delivery, Easy Returns, Value for Money with respect to Quality, Personal Buying Assistance, Volume Discounts, Credit Facilities, and the most important one, Guaranteed Lowest Prices!!! Shop at WholesaleBox, so that you can offer great pricing to your customers. In overall, buying at WholesaleBox will increase your profit margins at the convenience of your fingertips.';

$_['text_tabs_bottom_2'] = 'WholesaleBox is an online platform where retailers/shopkeepers can buy hasslefree and reduce their procurements costs at better quality, from the convenience of his/her home/shop. From WholesaleBox, a retailer can order products in bulk for reselling and the order will be delivered at his/her chosen place. The ordering process is pretty simple. Sign Up (if first time), or Login the website using your mobile number or email address. Select designs you wish to place the order for, and add them to your cart. Use filters, sorts, and search to get the desired products of your choice from more than %s+ to choose from. Once selection is complete, go to cart, click checkout and follow the steps to place the order with WholesaleBox and get Door Delivery done. Easy returns policy is provided post delivery of the Goods. Please review the Returns and Cancellation Policy.';
$_['text_tabs_bottom_3'] = 'WholesaleBox is a marketplace for wholesale buying and selling across India, connecting manufacturers or big wholesalers directly to retailers. We are a bunch of technology and business people from IIMs, IITs, NITs, etc, who are working to bring efficiency in the whole distribution system and help retailers get more variety at their doorsteps. They can take advantage of our simple web interface to buy products for their retail outlets and get those without having to travel to different cities / manufacturing hubs or to buy at much higher prices from the wholesalers near them. We\'ve put the entire wholesale buying process online to enable manufacturers & brands and retailers to drive incremental revenue, cut costs, improve their customer experience and analyze performance through data analytics.';

$_['text_tabs_bottom_co_1'] = 'We bring you wholesale boutique at the best prices, as we function at very low margins when compared with a normal Wholesaler near to you. Buying wholesale clothing from us, you can easily save 25%-35% of the procurement cost on the orders. We are comprised of more than %s+ wholesale womens clothing designs on our website for retailers accompanied with convenience of e-commerce like COD, Easy Returns, Home Delivery, Value for Money with respect to the Quality, Volume Discounts, Personal Buying Assistance, Credit Facilities, and the most prominent, Guaranteed Lowest Prices! We are the leading wholesale clothing suppliers & wholesalers online providing designer wholesale clothing, wholesale womens boutique clothing, wholesale children’s boutique clothing, wholesale plus size clothing & wholesale items at lowest wholesale factory prices.';

$_['text_tabs_bottom_co_2'] = 'WholesaleBox is the largest wholesale boutique & clothing online platform where retailers/shopkeepers can purchase hassle-free and reduce their procurements costs at quality oriented wholesale womens clothing & designer wholesale clothing from the convenience of his/her home/shop. From WholesaleBox- wholesale clothing suppliers & wholesalers online, a retailer can order products in bulk for reselling and the order will get delivered at his/her preferred place. The ordering process is very quick & simple. Sign Up (if first time), or Login the website using your mobile number or email address. Select wholesale womens boutique clothing, wholesale children’s boutique clothing, wholesale plus size clothing & wholesale items of your choice to place the order for, and just add them to your cart. Use filters, sorts, and search to get the desired products of your choice from the huge designer wholesale clothing collection. Once selection is done, go to cart, click checkout and follow the steps to place the order with WholesaleBox and get Door Delivery done. Easy returns policy is being provided post delivery of the products.';

$_['text_tabs_bottom_co_3'] = 'WholesaleBox is the leading wholesalers online providing wholesale womens boutique clothing, designer wholesale children’s boutique clothing, wholesale items & accessories, wholesale plus size clothing at the lowest wholesale factory prices. Being the top wholesale clothing suppliers worldwide, we have established ourselves as the largest marketplace for wholesale online shopping across worldwide which in turn connects manufacturers, big wholesalers to retailers. We are a team of technology and business people from IIMs, IITs, NITs, etc, who work to bring efficiency in the whole distribution system and help retailers get varied designer products at their doorsteps. Without any traveling effort to different cities/manufacturing hubs, the retailers can easily do wholesale online shopping from the wholesalers near them. This enables manufacturers, brands & retailers to boost up their revenue, cut cost and improve the overall customer experience.';

$_['text_change_language'] = 'Change Language';
$_['text_tab_info_1'] = 'Lowest Factory Prices Assured';
$_['text_tab_info_2'] = 'How Does Wholesalebox Work?';
$_['text_tab_info_3'] = 'About Wholesalebox';

//Track tpl

$_['text_app_download_link']   = 'https://play.google.com/store/apps/details?id=in.wholesalebox';
$_['text_redirect_msg']        = 'Redirect On Play Store...';
$_['text_users']           	 = 'Shops';
$_['text_designs']           = 'Designs';
$_['text_orders']           = 'Orders';
$_['text_latest_stats']           = 'Latest Stats';
$_['text_two_cashback'] = 'Purchase from our app and get 2% cashback for your next order within 7 days';
