CREATE DEFINER=`root`@`localhost` TRIGGER `update_order_backup_table` AFTER UPDATE ON `oc_suborder`
 FOR EACH ROW IF OLD.order_status_id = 0 and NEW.order_status_id=1 THEN
BEGIN
SET GLOBAL group_concat_max_len=16777215;
INSERT INTO oc_order_backup (order_id,suborder_id,tablename,detail,backup_time)
SELECT order_id,OLD.suborder_id,'oc_order',CONCAT('[',GROUP_CONCAT(JSON_OBJECT('order_id', order_id, 'order_no', order_no,'store_id',store_id, 'store_name', store_name, 'store_url', store_url, 'customer_id', customer_id, 'customer_group_id', customer_group_id, 'firstname', firstname, 'lastname', lastname, 'email', email, 'telephone', telephone, 'fax', fax, 'custom_field', custom_field, 'payment_firstname', payment_firstname, 'payment_lastname', payment_lastname, 'payment_company', payment_company, 'payment_address_1', payment_address_1, 'payment_address_2', payment_address_2, 'payment_city', payment_city, 'payment_postcode', payment_postcode, 'payment_country', payment_country, 'payment_country_id', payment_country_id, 'payment_zone', payment_zone, 'payment_zone_id', payment_zone_id, 'payment_address_format', payment_address_format, 'payment_custom_field', payment_custom_field, 'payment_method', payment_method, 'payment_code', payment_code, 'shipping_firstname', shipping_firstname, 'shipping_lastname', shipping_lastname, 'shipping_company', shipping_company, 'shipping_address_1', shipping_address_1, 'shipping_address_2', shipping_address_2, 'shipping_city', shipping_city, 'shipping_postcode', shipping_postcode, 'shipping_country',shipping_country , 'shipping_country_id', shipping_country_id, 'shipping_zone', shipping_zone, 'shipping_zone_id', shipping_zone_id, 'shipping_address_format', shipping_address_format, 'shipping_custom_field', shipping_custom_field, 'comment', comment, 'total', total, 'affiliate_id', affiliate_id, 'commission', commission, 'marketing_id', marketing_id, 'tracking', tracking, 'language_id', language_id, 'currency_id', currency_id, 'currency_code', currency_code, 'currency_value', currency_value, 'live_currency_conversion_rate', live_currency_conversion_rate, 'ip', ip, 'forwarded_ip', forwarded_ip, 'user_agent', user_agent, 'accept_language', accept_language, 'date_added', date_added, 'date_modified', date_modified, 'sales_staff_id', sales_staff_id, 'order_from', order_from, 'bank_slip_image', bank_slip_image, 'shipping_charge', shipping_charge, 'weight_class_id', weight_class_id, 'store_voucher', store_voucher, 'code_version', code_version, 'gst_number', gst_number, 'stock_transfer', stock_transfer, 'gst_unregister_declared', gst_unregister_declared)),']'),NOW() FROM `oc_order` o
WHERE o.order_id=OLD.order_id;
INSERT INTO oc_order_backup (order_id,suborder_id,tablename,detail,backup_time)
SELECT order_id,OLD.suborder_id,'oc_suborder',CONCAT('[',GROUP_CONCAT(JSON_OBJECT('order_id', order_id, 'suborder_id', suborder_id, 'invoice_no', invoice_no, 'invoice_date', invoice_date, 'invoice_prefix', invoice_prefix, 'shipping_method', shipping_method, 'shipping_code', shipping_code, 'total', total, 'order_status_id', order_status_id, 'date_added', date_added, 'date_modified', date_modified, 'cform_submit', cform_submit, 'cst_with_cform', cst_with_cform, 'refundable_cform', refundable_cform, 'refund_status', refund_status, 'courier_partner', courier_partner, 'tracking_no', tracking_no, 'shipping_charge', shipping_charge, 'custom_totals', custom_totals, 'gst', gst)),']'),NOW() FROM `oc_suborder` sub
WHERE sub.suborder_id=OLD.suborder_id;
INSERT INTO oc_order_backup (order_id,suborder_id,tablename,detail,backup_time)
SELECT order_id,OLD.suborder_id,'oc_order_product',CONCAT('[',GROUP_CONCAT(JSON_OBJECT('order_product_id', order_product_id, 'order_id', order_id, 'suborder_id', suborder_id, 'product_id', product_id, 'seller_id', seller_id, 'seller_invoice_id', seller_invoice_id, 'name', name, 'model', model, 'quantity', quantity, 'piece_in_set', piece_in_set, 'price_per_piece', price_per_piece, 'discount_per_piece', discount_per_piece, 'discount_breakup', discount_breakup, 'weight_per_piece', weight_per_piece, 'tax', tax, 'output_tax_rates', output_tax_rates, 'reward', reward, 'comment', comment, 'seller_sku', seller_sku, 'transfer_price_per_piece', transfer_price_per_piece, 'seller_input_tax', seller_input_tax, 'seller_cst', seller_cst, 'store_sales', store_sales, 'store_pickup', store_pickup, 'customer_comment', customer_comment, 'edit_type', edit_type, 'edit_history', edit_history, 'hsn_code', hsn_code, 'pickup_status', pickup_status, 'pickup_last_modified', pickup_last_modified, 'pickup_history', pickup_history)),']'),NOW() FROM `oc_order_product` op
WHERE op.suborder_id=OLD.suborder_id;
INSERT INTO oc_order_backup (order_id,suborder_id,tablename,detail,backup_time)
SELECT order_id,OLD.suborder_id,'oc_order_option',CONCAT('[',GROUP_CONCAT(JSON_OBJECT('order_option_id', order_option_id, 'order_id', order_id, 'suborder_id', suborder_id, 'order_product_id', order_product_id, 'product_option_id', product_option_id, 'product_option_value_id', product_option_value_id, 'name', name, 'value', value, 'type', type)),']'),NOW() FROM `oc_order_option` opsn
WHERE opsn.suborder_id=OLD.suborder_id;
END;