-- phpMyAdmin SQL Dump
-- version 4.5.4.1deb2ubuntu2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jan 06, 2017 at 07:23 PM
-- Server version: 5.7.16-0ubuntu0.16.04.1
-- PHP Version: 7.0.8-0ubuntu0.16.04.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `wholesalebox`
--

-- --------------------------------------------------------

--
-- Table structure for table `oc_paperwork`
--

CREATE TABLE `oc_paperwork` (
  `zone_id` int(11) NOT NULL,
  `state` varchar(128) CHARACTER SET utf8 NOT NULL,
  `b2c_stat_levy_type` varchar(30) CHARACTER SET utf8 NOT NULL,
  `b2c_stat_levy_liable` varchar(25) CHARACTER SET utf8 NOT NULL,
  `b2c_paperwork_req` varchar(60) CHARACTER SET utf8 NOT NULL,
  `b2c_paperwork_exem_lim` varchar(20) CHARACTER SET utf8 NOT NULL,
  `b2b_paperwork_inb_req` varchar(60) CHARACTER SET utf8 NOT NULL,
  `b2b_paperwork_outb_req` varchar(60) CHARACTER SET utf8 NOT NULL,
  `additional_notes` text CHARACTER SET utf8 NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `oc_paperwork`
--

INSERT INTO `oc_paperwork` (`zone_id`, `state`, `b2c_stat_levy_type`, `b2c_stat_levy_liable`, `b2c_paperwork_req`, `b2c_paperwork_exem_lim`, `b2b_paperwork_inb_req`, `b2b_paperwork_outb_req`, `additional_notes`) VALUES
(1476, 'Andhra Pradesh', 'Nil', '', 'Consumer Invoice', 'Nil', 'Consumer Invoice + VAT Form x/600(online)', 'CI + VAT Form x/600(online)', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1475, 'Andaman & Nicobar', 'Nil', '', 'Consumer Invoice', 'Nil', 'Consumer Invoice', '', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1477, 'Arunachal Pradesh', 'Entry Tax', 'Consignee', 'Consumer Invoice', '<10,000', 'Consumer Invoice + RC of consignee**', '', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.Self certified copy of Registration certificate of consignee is required to move the ship to Arunachal pardesh.'),
(1478, 'Assam', 'Entry Tax*', 'Carrier*', 'Consumer Invoice(B2C e-commerce)/From 62', 'Nil', 'Consumer Invoice + VAT Form 61(manual)', 'Consumer Invoice + VAT Form 63', 'Entry permit for e-commerce B2C shipments (Air  mode) to Assam , odisha, West Bengal & Bihar is exempted subject to payment of Entry Tax. VAT from is applicable for normal B2C,B2B & C2C shipments . Shipper will rimburse Fedex for any payments of entry tax made on its behalf. Please contact is interested in availling of the service. Entry Tax process for Asssam, odisha & Bihar under surface mode is not yet started. COD service is suspended for kerala. '),
(1479, 'Bihar', 'Entry Tax', 'Carrier*', 'Consumer Invoice+VAT From D IX(online)', '<10,000', 'Consumer Invoice +VAT From D IX for>INR 10,000(online)', 'Consumer Invoice + VAT Form D IX for>INR 10K(online)', 'Entry permit for e-commerce B2C shipments (Air  mode) to Assam , odisha, West Bengal & Bihar is exempted subject to payment of Entry Tax. VAT from is applicable for normal B2C,B2B & C2C shipments . Shipper will rimburse Fedex for any payments of entry tax made on its behalf. Please contact is interested in availling of the service. Entry Tax process for Asssam, odisha & Bihar under surface mode is not yet started. COD service is suspended for kerala. '),
(1480, 'Chandigarh', 'Nil', '', 'Consumer Invoice', 'Nil', 'Consumer Invoice', '', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(4232, 'Chhattisgarh', 'Nil', '', 'Consumer Invoice', 'Nil', 'Consumer Invoice', '', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1481, 'Dadra & Nager Haveli', 'Nil', '', 'Consumer Invoice', 'Nil', 'Consumer Invoice', '', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1482, 'Daman & Diu', 'Nil', '', 'Consumer Invoice', 'Ni!', 'Consumer Invoice', '', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1483, 'Delhi', 'Nil', '', 'Consumer Invoice', 'Nil', 'Consumer Invoice+VAT From D2S(online)', '', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1484, 'Goa', 'Nil', '', 'Consumer Invoice', 'Nil', 'Consumer Invoice', '', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1485, 'Gujarat', 'Entry Tax', 'eComm Shipper', 'Consumer Invoice + VAT From 403(online-eComm)', 'Nil', 'Consumer Invoice + VAT Form 403(online)', 'Consumer Invoice + VAT 402(online)', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1486, 'Haryana', 'Nil', '', 'Consumer Invoice', 'Nil', 'Consumer Invoice', '', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1487, 'Himachal Pradesh', 'Entry Tax', 'Consignee / Carrier', 'Consumer Invoice', 'Nil', 'Consumer Invoice', 'Consumer Invoice+ VAT Form  5048(online)', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1488, 'Jammu & Kashmir', 'Entry Tax', 'Consignee / Carrier', 'Consumer Invoice', '<5,000', 'Consumer Invoice + VAT Form 65(manual/online)', '', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(4233, 'Jharkhand', 'Nil', '', 'CI + VAT Form 503(manual)', 'Nil', 'Consumer Invoice +VAT Form 504 G (online)', 'Consumer Invoice +VAT Form 5048B(online)', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1489, 'Karnataka', 'Nil', '', 'Consumer Invoice', 'Nil', 'Consumer Invoice + e-Sugam(online)', 'Consumer Invoice_e\\Sugam for > INR25k', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1490, 'Kerala', 'Nil', '', 'Consumer Invoice + From 16(manual/online)', '<5,000(pre-paid)', 'Consumer Invoice + 8 FA(air) / Transaction slip (surface)', 'Consumer Invoice +VAT Form 15(online)', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1491, 'Lakshadweep', 'Nil', '', 'Consumer Invoice', 'Nil', 'Consumer Invoice', '', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1492, 'Madhya Pradesh', 'Entry TAx', 'Carrier', 'Consumer Invoice+ From XVII(carrier to generate)', 'Nil', 'Consumer Invoice + VAT Form 49 online', 'Consumer Invoice+ Form 49(out)(online) for notified goods ', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1493, 'Maharashtra', 'Octroi or LBT***', 'Carrier', 'Shipper InvoiceConsumer Invoice', '<150', 'Consumer Invoice***', '', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.LBT registration of shippers is mandatory for e-commerce B2C COD shipments to LBT zones in maharashtra. LBT registration number of shipper should be mentioned on invoice.'),
(1494, 'Manipur', 'Nil', '', 'Consumer Invoice + VAT Form 37', 'Nil', 'Consumer Invoice +VAT Form 27(online) ', 'Consumer Invoice +VAT Form 28(online) ', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1495, 'Meghalaya', 'Nil', '', 'Consumer Invoice+ Special permit', 'Nil', 'Consumer Invoice + VAT Form 40(online)', 'Consumer Invoice +VAT Form 37 for taxable goods', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1496, 'Mizoram', 'Nil', '', 'Consumer Invoice + VAT Form 34(manual)', 'Nil', 'Consumer Invoice+VAT From 33', '', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1497, 'Nagaland', 'Nil', '', 'Consumer Invoice+ VAT Form 23(manual)', '', 'Consumer Invoice+ VAT Form 23 (online)', '', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1498, 'Orissa', 'Entry Tax*', 'Carrier*', 'Consumer Invoice(e-commerce)/402A', 'Nil', 'Consumer Invoice+ VAT Form 402 (online )', 'Consumer Invoice+VAT Form 402', 'Entry permit for e-commerce B2C shipments (Air  mode) to Assam , odisha, West Bengal & Bihar is exempted subject to payment of Entry Tax. VAT from is applicable for normal B2C,B2B & C2C shipments . Shipper will rimburse Fedex for any payments of entry tax made on its behalf. Please contact is interested in availling of the service. Entry Tax process for Asssam, odisha & Bihar under surface mode is not yet started. COD service is suspended for kerala. '),
(1499, 'Pondicherry', 'Nil', '', 'Consumer Invoice', 'Nil', 'Consumer Invoice', '', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1500, 'Punjab', 'Entry fee', 'carrier', 'Consumer Invoice + Carrier Entry Form (online)', 'Consumer Invoice', 'Consumer Invoice', 'Consumer Invoice +VAT From 402', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1501, 'Rajasthan', 'Entry Tax', 'Consignee', 'Consumer Invoice', 'Nil', 'Consumer Invoice + VAT Form 47/47A ( online )', 'Consumer Invoice +VAT Form 49A(online)/49(manual)', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1502, 'Sikkim', 'Nil', '', 'Consumer Invoice + special permit(manual)', 'Nil', 'Consumer Invoice+ VAT From 25/27(online)', 'Consumer Invoice + VAT Form 26', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1503, 'Tamil Nadu', 'Nil', '', 'Consumer Invoice', 'Nil', 'Consumer Invoice +VAT Form JJ(online) for notifed goods', 'Consumer Invoice +VAT Form JJ(online) for notifed goods', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(4231, 'Telangana', 'Nil', '', 'Consumer Invoice +VAT Form JJ(online) for notifed goods', 'Nil', 'Consumer Invoice +VAT Form X/6000 for notified goods', '', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1504, 'Tripura', 'Nil', '', 'Consumer Invoice+ VAT Permit(manual)', '', 'Consumer Invoice +VAT FROM XXIV(online)', 'Consumer Invoice+ VAT FROM XXIV', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(1505, 'Uttar Pradesh', 'Entry TAX', '', 'Consumer Invoice + EC Form (carrier to generate)', 'Nil', 'Consumer Invoice +VAT e-sancharan/manual form 38>INR 5K', '', 'Intra-India shipments of the commodities in exemption lists of VAT regulations of the destination state are not subject to any VAT form under B2C & B2B shipments.TIN number of shipper Consignee is mandatory on commercial invoice in case of B2B (and of shipper in case ofB2C). Fedex has suspended w-commerce B2C COD shipments to Kerala.VAT Form (wherever applicable) may be for select goods or select category of dealers. Pls visit the destination state VAT website for further information.Declaration from consignee may be required in case of B2C / C2C movements as per the destination state requirement.Gift or sample shipments to Arunachal Pradesh up to a value of INR 10,000 (declared on Invoice) are exempt from Entry Tax.Entry Tax is charged on selected commodity as listed under the destination state\'s VAT website.'),
(4234, 'Uttrakhand', 'Entry TAX*', 'Carrier*', 'Consumer Invoice+ e-commerce / Form17 ', 'Nil', 'Consumer Invoice + VAT Form 16(manual/online)>INR 5K', '', 'Entry permit for e-commerce B2C shipments (Air  mode) to Assam , odisha, West Bengal & Bihar is exempted subject to payment of Entry Tax. VAT from is applicable for normal B2C,B2B & C2C shipments . Shipper will rimburse Fedex for any payments of entry tax made on its behalf. Please contact is interested in availling of the service. Entry Tax process for Asssam, odisha & Bihar under surface mode is not yet started. COD service is suspended for kerala. '),
(1506, 'West Bengal', 'Entry Tax*', 'Carrier*', 'Consumer Invoice (e-commmerce) / Form 50A/50', 'Nil', 'Consumer Invoice+ VAT Form 50A(online)', 'XI + VAT Form 51', 'Entry permit for e-commerce B2C shipments (Air  mode) to Assam , odisha, West Bengal & Bihar is exempted subject to payment of Entry Tax. VAT from is applicable for normal B2C,B2B & C2C shipments . Shipper will rimburse Fedex for any payments of entry tax made on its behalf. Please contact is interested in availling of the service. Entry Tax process for Asssam, odisha & Bihar under surface mode is not yet started. COD service is suspended for kerala. ');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `oc_paperwork`
--
ALTER TABLE `oc_paperwork`
  ADD PRIMARY KEY (`zone_id`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
